name: TweakedCycle
main: tzer0.TweakedCycle.TweakedCycle
version: 1.0
author: TZer0
commands:
    tc:
        description: Tweaks day-night cycles.
        usage: /tc
    tweakedcycle:
        description: Tweaks day-night cycles.
        usage: /tweakedcycle
